### ISSUE TITLE
[Bug]: HEIF not supported by GIMP 3.0.0 (24.04)

### ISSUE THREAD

**Issue by pieroxy** [snapcrafters/gimp#390]
### What happened?

One of the new things in Ubuntu 24.04 if the HEIF support all over: Nautilus, image viewer, etc. 
Also, GIMP's version coming from aptitude (gimp 2.10.36) dose support HEIF without any issue.

Not sure that's a bug but it certainly is an oddity, especially considering the ubiquitous nature of HEIF these days. 

### What should have happened?

As the rest of the applications on Ubuntu 24.04, I expected to be able to open HEIF files.

### Output of `snap info $snap_name`

```shell
name:      gimp
summary:   GNU Image Manipulation Program
publisher: Snapcrafters✪
store-url: https://snapcraft.io/gimp
contact:   https://github.com/snapcrafters/gimp/issues
license:   GPL-3.0+
description: |
  Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you
  with sophisticated tools to get your job done. You can further enhance your productivity with GIMP
  thanks to many customization options and 3rd party plugins.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
  
  Upstream Project: https://www.gimp.org/
  snapcraft.yaml Build Definition:
  https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml
snap-id: KDHYbyuzZukmLhiogKiUksByRhXD2gYV
channels:
  latest/stable:           3.0.0   2025-03-18 (502) 323MB -
  latest/candidate:        3.0.2   2025-03-25 (507) 278MB -
  latest/beta:             ↑                              
  latest/edge:             3.0.2   2025-03-25 (506) 278MB -
  preview/stable:          3.0.0   2025-03-18 (498) 323MB -
  preview/candidate:       3.0.0   2025-03-18 (498) 323MB -
  preview/beta:            ↑                              
  preview/edge:            3.0.0   2025-03-18 (500) 323MB -
  2.99-openvino/stable:    2.99.16 2025-01-21 (481) 387MB -
  2.99-openvino/candidate: 2.99.16 2025-01-14 (481) 387MB -
  2.99-openvino/beta:      ↑                              
  2.99-openvino/edge:      ↑
```

### Output of `snap connections $snap_name`

```shell
Interface               Plug                                           Slot                            Notes
browser-support         gimp:browser-support                           :browser-support                -
content[ffmpeg-2404]    gimp:ffmpeg-2404                               ffmpeg-2404:ffmpeg-2404         -
content[gnome-46-2404]  gimp:gnome-46-2404                             gnome-46-2404:gnome-46-2404     -
content[gpu-2404]       gimp:gpu-2404                                  mesa-2404:gpu-2404              -
content[gtk-3-themes]   gimp:gtk-3-themes                              gtk-common-themes:gtk-3-themes  -
content[icon-themes]    gimp:icon-themes                               gtk-common-themes:icon-themes   -
content                 gimp:npu-libs                                  -                               -
content                 gimp:openvino-ai-plugins-gimp-libs             -                               -
content                 gimp:openvino-libs                             -                               -
content[sound-themes]   gimp:sound-themes                              gtk-common-themes:sound-themes  -
cups-control            gimp:cups-control                              -                               -
custom-device           gimp:intel-npu                                 -                               -
dbus                    -                                              gimp:dbus-gimp                  -
desktop                 gimp:desktop                                   :desktop                        -
desktop-legacy          gimp:desktop-legacy                            :desktop-legacy                 -
gsettings               gimp:gsettings                                 :gsettings                      -
home                    gimp:home                                      :home                           -
network                 gimp:network                                   :network                        -
opengl                  gimp:opengl                                    :opengl                         -
personal-files          gimp:dot-local-share-openvino-ai-plugins-gimp  :personal-files                 -
removable-media         gimp:removable-media                           -                               -
unity7                  gimp:unity7                                    :unity7                         -
wayland                 gimp:wayland                                   :wayland                        -
x11                     gimp:x11                                       :x11                            -
```

### Output of `snap version`

```shell
snap    2.67.1+24.04
snapd   2.67.1+24.04
series  16
ubuntu  24.04
kernel  6.8.0-56-generic
```

### Relevant log output

```shell
Opening '/some/folder/IMG_XXX.HEIC' failed:

Unknown file type
```

### Teminal output of app

```shell

```

**Comment by jnsgruk** [comment]
Hmm, it's not obvious to me why this doesn't work. The GIMP docs state that HEIF support should be there by default in the form of a plugin, but I don't see it shipped in the snap (though I do see libheif is present, at least).

EDIT: It might be a build flag, just experimenting locally!

**Comment by pieroxy** [comment]
FYI, there is discussion on askubuntu about this: https://askubuntu.com/questions/1544748/ubuntu-24-04-gimp-2-10-36-can-open-heif-files-but-gimp-3-0-0-cannot

**Comment by jnsgruk** [comment]
Yup, looks like the build environment doesn't include `libheif-dev`, which led to the feature not being configured... just fixing this locally and will push a new build

reference: https://github.com/snapcrafters/gimp/actions/runs/14055024918/job/39352504259#step:3:6386

**Comment by pieroxy** [comment]
That's great news! Thanks a lot.

Do you have an idea when we can expect the fix to be rolled out ?

**Comment by jnsgruk** [comment]
Added support in [this commit](https://github.com/snapcrafters/gimp/commit/d56e12ab7e4f73a32e0a74bfe9da162bf3fc808e).

It'll be a couple of days before this lands in the `stable` channel, but you can do the following now to try it out:

```
sudo snap refresh gnome-46-2404 --channel latest/candidate
sudo snap refresh gimp --channel latest/edge
```

Let me know how it goes!

**Comment by jnsgruk** [comment]
This should now be solved (https://github.com/snapcrafters/gimp/issues/405). Thanks everyone for your patience! You can get the latest release with:

```
sudo snap refresh gimp --channel latest/stable
```

**Comment by pieroxy** [comment]
I just installed gimp 3.0.2 from snap (released yesterday) and I still have the same problem... Is there another package I need to install to have HEIF support ?

![Image](https://github.com/user-attachments/assets/d747933e-092c-409e-b09c-1b734c359174)

**Comment by jnsgruk** [comment]
Hmm, right you are. Will try to take a look at this, but I'm going to be afk for a while. Perhaps @soumyaDghosh or @lucyllewy might have some ideas?

EDIT: Strangely, it does still show as configured during the build, but I also can't open HEIC files (https://github.com/snapcrafters/gimp/actions/runs/14265554618/job/40235581593#step:3:6386)

**Comment by jnsgruk** [comment]
Also maybe @jehan might be able to give some context (thank you for your assistance on the last issue!)

As far as I can tell, the build is configured for it, and if I look in the snap's directory I can see the `file-heif` plugin...

```
❯ fd heif /snap/gimp/current | xargs ls -la
-rwxr-xr-x 1 root root 72888 Apr  9 10:15 /snap/gimp/current/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-heif/file-heif

/snap/gimp/current/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-heif/:
total 72
drwxr-xr-x   2 root root    32 Apr  9 10:29 .
drwxr-xr-x 124 root root  2298 Apr  9 10:29 ..
-rwxr-xr-x   1 root root 72888 Apr  9 10:15 file-heif

/snap/gimp/current/usr/lib/x86_64-linux-gnu/libheif/:
total 0
drwxr-xr-x  3 root root    30 Oct 21 11:48 .
drwxr-xr-x 33 root root 10863 Apr  9 10:30 ..
drwxr-xr-x  2 root root     3 Apr  9 10:30 plugins

/snap/gimp/current/usr/share/doc/libheif1/:
total 9
drwxr-xr-x   2 root root   59 Apr  9 10:29 .
drwxr-xr-x 315 root root 6791 Apr  9 10:29 ..
lrwxrwxrwx   1 root root   44 Oct 21 11:48 changelog.Debian.gz -> ../libheif-plugin-aomdec/changelog.Debian.gz
-rw-r--r--   1 root root 8636 Apr 16  2024 copyright

/snap/gimp/current/usr/share/doc/libheif-plugin-aomdec/:
total 12
drwxr-xr-x   2 root root   59 Apr  9 10:29 .
drwxr-xr-x 315 root root 6791 Apr  9 10:29 ..
-rw-r--r--   1 root root 2889 Oct 21 11:48 changelog.Debian.gz
-rw-r--r--   1 root root 8636 Apr 16  2024 copyright

/snap/gimp/current/usr/share/doc/libheif-plugin-libde265/:
total 9
drwxr-xr-x   2 root root   59 Apr  9 10:29 .
drwxr-xr-x 315 root root 6791 Apr  9 10:29 ..
lrwxrwxrwx   1 root root   44 Oct 21 11:48 changelog.Debian.gz -> ../libheif-plugin-aomdec/changelog.Debian.gz
-rw-r--r--   1 root root 8636 Apr 16  2024 copyright
```

And it seems to point to the right places for `libheif`:

```
jon@kara:/snap/gimp/current$ ldd /snap/gimp/current/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-heif/file-heif
        linux-vdso.so.1 (0x000070d1f9090000)
        /snap/gimp/510/gnome-platform/$LIB/bindtextdomain.so => /snap/gimp/510/gnome-platform/lib/x86_64-linux-gnu/bindtextdomain.so (0x000070d1f9075000)
        libgimp-3.0.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgimp-3.0.so.0 (0x000070d1f8fe9000)
        libgimpbase-3.0.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgimpbase-3.0.so.0 (0x000070d1f8faa000)
        libgimpcolor-3.0.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgimpcolor-3.0.so.0 (0x000070d1f8f91000)
        libgimpui-3.0.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgimpui-3.0.so.0 (0x000070d1f8f5d000)
        libgimpwidgets-3.0.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgimpwidgets-3.0.so.0 (0x000070d1f8cc8000)
        libgtk-3.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-3.so.0 (0x000070d1f847b000)
        libgdk_pixbuf-2.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x000070d1f8447000)
        libgio-2.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x000070d1f822f000)
        libgobject-2.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x000070d1f81bf000)
        libglib-2.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x000070d1f8046000)
        libgegl-0.4.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgegl-0.4.so.0 (0x000070d1f7f32000)
        libbabl-0.1.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libbabl-0.1.so.0 (0x000070d1f7ddc000)
        libheif.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libheif.so.1 (0x000070d1f7d1c000)
        libgexiv2.so.2 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgexiv2.so.2 (0x000070d1f7ce3000)
        liblcms2.so.2 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x000070d1f7c81000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x000070d1f7a5e000)
        libgimpconfig-3.0.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgimpconfig-3.0.so.0 (0x000070d1f7a3d000)
        libcairo.so.2 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x000070d1f78c6000)
        libpango-1.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x000070d1f784c000)
        libfontconfig.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x000070d1f77fb000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x000070d1f7712000)
        libgimpmodule-3.0.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgimpmodule-3.0.so.0 (0x000070d1f7708000)
        libgdk-3.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0 (0x000070d1f75e9000)
        libpangocairo-1.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x000070d1f75d7000)
        libgmodule-2.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x000070d1f75d0000)
        libharfbuzz.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x000070d1f743e000)
        libpangoft2-1.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x000070d1f741f000)
        libfribidi.so.0 => /snap/gimp/510/ffmpeg-platform/usr/lib/x86_64-linux-gnu/libfribidi.so.0 (0x000070d1f7401000)
        libcairo-gobject.so.2 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x000070d1f73f6000)
        libatk-1.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x000070d1f73cc000)
        libepoxy.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libepoxy.so.0 (0x000070d1f729a000)
        libXi.so.6 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libXi.so.6 (0x000070d1f7285000)
        libX11.so.6 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libX11.so.6 (0x000070d1f7148000)
        libatk-bridge-2.0.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x000070d1f7106000)
        libXfixes.so.3 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x000070d1f70fe000)
        libpng16.so.16 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x000070d1f70c6000)
        libjpeg.so.8 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x000070d1f7041000)
        libz.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libz.so.1 (0x000070d1f7025000)
        libmount.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libmount.so.1 (0x000070d1f6fd8000)
        libselinux.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libselinux.so.1 (0x000070d1f6fab000)
        libffi.so.7 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libffi.so.7 (0x000070d1f6f9e000)
        /lib64/ld-linux-x86-64.so.2 (0x000070d1f9092000)
        libpcre2-8.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x000070d1f6f02000)
        libsharpyuv.so.0 => /snap/gimp/510/ffmpeg-platform/usr/lib/x86_64-linux-gnu/libsharpyuv.so.0 (0x000070d1f6efa000)
        libstdc++.so.6 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x000070d1f6c7c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x000070d1f6c4e000)
        libexiv2.so.27 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libexiv2.so.27 (0x000070d1f695e000)
        libgimpmath-3.0.so.0 => /snap/gimp/510/usr/lib/x86_64-linux-gnu/libgimpmath-3.0.so.0 (0x000070d1f6954000)
        libfreetype.so.6 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x000070d1f6888000)
        libXext.so.6 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libXext.so.6 (0x000070d1f6874000)
        libXrender.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x000070d1f6868000)
        libxcb.so.1 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x000070d1f683f000)
        libxcb-render.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libxcb-render.so.0 (0x000070d1f682e000)
        libxcb-shm.so.0 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x000070d1f6829000)
        libpixman-1.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libpixman-1.so.0 (0x000070d1f671e000)
        libthai.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libthai.so.0 (0x000070d1f6713000)
        libexpat.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libexpat.so.1 (0x000070d1f66e8000)
        libxkbcommon.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x000070d1f669d000)
        libwayland-client.so.0 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x000070d1f668d000)
        libwayland-cursor.so.0 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x000070d1f6683000)
        libwayland-egl.so.1 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x000070d1f667e000)
        libXcursor.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x000070d1f6672000)
        libXdamage.so.1 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x000070d1f666b000)
        libXcomposite.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libXcomposite.so.1 (0x000070d1f6666000)
        libXrandr.so.2 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x000070d1f6659000)
        libXinerama.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x000070d1f6654000)
        libgraphite2.so.3 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x000070d1f662e000)
        libatspi.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libatspi.so.0 (0x000070d1f65e9000)
        libdbus-1.so.3 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libdbus-1.so.3 (0x000070d1f659a000)
        libblkid.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libblkid.so.1 (0x000070d1f655f000)
        libbz2.so.1.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libbz2.so.1.0 (0x000070d1f654b000)
        libbrotlidec.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x000070d1f653b000)
        libXau.so.6 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libXau.so.6 (0x000070d1f6535000)
        libXdmcp.so.6 => /snap/gimp/510/gpu-2404/usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x000070d1f652d000)
        libdatrie.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libdatrie.so.1 (0x000070d1f6524000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x000070d1f6518000)
        libsystemd.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libsystemd.so.0 (0x000070d1f6436000)
        libbrotlicommon.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x000070d1f6413000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x000070d1f63fd000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x000070d1f63f0000)
        libgcrypt.so.20 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x000070d1f62a8000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x000070d1f6284000)
        liblzma.so.5 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/liblzma.so.5 (0x000070d1f6252000)
        libzstd.so.1 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x000070d1f6198000)
        libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x000070d1f6189000)
        libgpg-error.so.0 => /snap/gimp/510/gnome-platform/usr/lib/x86_64-linux-gnu/libgpg-error.so.0 (0x000070d1f6164000)
```

When I start with `gimp --verbose` I also see:

```
Parsing '/home/jon/snap/gimp/510/.config/GIMP/3.0/pluginrc'
Querying plug-in: '/snap/gimp/510/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-rawtherapee/file-rawtherapee'
Querying plug-in: '/snap/gimp/510/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-heif/file-heif'
Querying plug-in: '/snap/gimp/510/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-darktable/file-darktable'
Initializing plug-in: '/snap/gimp/510/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/mail/mail'
Initializing plug-in: '/snap/gimp/510/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-rawtherapee/file-rawtherapee'
Initializing plug-in: '/snap/gimp/510/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-heif/file-heif'
Initializing plug-in: '/snap/gimp/510/usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-darktable/file-darktable'
```

**Comment by Jehan** [comment]
I have not looked at the whole comments, but `libheif` itself can have various encoders/decoders compiled in. This is all detailed in our [`INSTALL`](https://developer.gimp.org/core/setup/build/3.0/INSTALL) (also in the repo):

     Make sure you build libheif with libde265 and libx265 support (for
     respectively decoding and encoding of HEVC, i.e. HEIC files), and
     libaom decoder and encoder (for AV1, i.e. AVIF files), otherwise
     the plug-in is mostly useless.

**Comment by Jehan** [comment]
P.S.: the accurate support (HEIC and/or AVIF) is verified at runtime, since these encoders/decoders can be added as separate modules. So that's why the `file-heif` plug-in may be present and "working" yet not actually supporting anything (or maybe just AVIF, or maybe just HEIC).

**Comment by jnsgruk** [comment]
Hmm, thanks for the tip, though it looks like the `libheif` that was built already supports that (or at least I think it does, based on the `aomdec` and `libde265` plugins):

```
/snap/gnome-46-2404/current🔒
❯ fd heif
usr/lib/x86_64-linux-gnu/cmake/libheif/
usr/lib/x86_64-linux-gnu/cmake/libheif/libheif-config-none.cmake
usr/lib/x86_64-linux-gnu/cmake/libheif/libheif-config-version.cmake
usr/lib/x86_64-linux-gnu/cmake/libheif/libheif-config.cmake
usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-heif.so
usr/lib/x86_64-linux-gnu/libheif/
usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-aomdec.so
usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-libde265.so
usr/lib/x86_64-linux-gnu/libheif.so
usr/lib/x86_64-linux-gnu/libheif.so.1
usr/lib/x86_64-linux-gnu/libheif.so.1.17.6
usr/share/mime/image/heif.xml
```

EDIT: and indeed looking at the build recipe, all the plugins seem to be enabled: https://git.launchpad.net/ubuntu/+source/libheif/tree/debian/rules?h=ubuntu/noble-updates

**Comment by jnsgruk** [comment]
Okay, I just tried building `libheif` from source in the snap, and I'm still getting the same problem, so I'm starting to wonder if this is indeed a problem with Gimp itself?

This is the patch I used to build libheif in the snap:

```diff
diff --git i/snap/snapcraft.yaml w/snap/snapcraft.yaml
index 169886d..e88747f 100644
--- i/snap/snapcraft.yaml
+++ w/snap/snapcraft.yaml
@@ -81,7 +81,7 @@ apps:
     common-id: org.gimp.GIMP
     environment:
       HOME: $SNAP_REAL_HOME
-      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
+      LD_LIBRARY_PATH: $SNAP/usr/local/lib:$SNAP/usr/local/lib/libheif:$SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
       PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
     slots:
       - dbus-gimp
@@ -170,10 +170,23 @@ parts:
     build-snaps:
       - ffmpeg-2404
 
+  libheif:
+    plugin: cmake
+    source: https://github.com/strukturag/libheif.git
+    source-type: git
+    cmake-parameters:
+      - --preset=release
+    override-build: |
+      cd $CRAFT_PART_SRC
+      bash ./third-party/aom.cmd
+      export PKG_CONFIG_PATH=\$PKG_CONFIG_PATH:$(pwd)/aom/dist/lib/pkgconfig
+      craftctl default
+
   gimp:
     after:
       - babl
       - gegl
+      - libheif
     plugin: meson
     source: https://github.com/GNOME/gimp.git
     override-pull: |
@@ -197,7 +210,7 @@ parts:
       - GEGL_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gegl-0.4
       - GI_TYPELIB_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:$GI_TYPELIB_PATH
       - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
-      - C_INCLUDE_PATH: /snap/gnome-46-2404-sdk/current/usr/include/librsvg-2.0:${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}
+      - C_INCLUDE_PATH: $CRAFT_STAGE/usr/local/include:/snap/gnome-46-2404-sdk/current/usr/include/librsvg-2.0:${C_INCLUDE_PATH:+:$C_INCLUDE_PATH}
     build-packages:
       - automake
       - intltool
@@ -213,7 +226,6 @@ parts:
       - libfftw3-dev
       - libgexiv2-dev
       - libgpm-dev
-      - libheif-dev
       - libice-dev
       - libluajit-5.1-dev
       - libjxl-dev
@@ -245,8 +257,6 @@ parts:
       - libfftw3-double3
       - libgexiv2-2
       - libgpm2
-      - libheif-plugin-libde265
-      - libheif1
       - libjxl0.7
       - libluajit-5.1-2
       - liblzma5
```

Doing some digging, things seem to be in order in the snap:

```
jon@kara:/snap/gimp/current$ find . -type f -name *heif*
./usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-heif/file-heif
./usr/local/bin/heif-dec
./usr/local/bin/heif-enc
./usr/local/bin/heif-info
./usr/local/bin/heif-thumbnailer
./usr/local/include/libheif/heif.h
./usr/local/include/libheif/heif_cxx.h
./usr/local/include/libheif/heif_items.h
./usr/local/include/libheif/heif_plugin.h
./usr/local/include/libheif/heif_properties.h
./usr/local/include/libheif/heif_regions.h
./usr/local/include/libheif/heif_version.h
./usr/local/lib/cmake/libheif/libheif-config-release.cmake
./usr/local/lib/cmake/libheif/libheif-config-version.cmake
./usr/local/lib/cmake/libheif/libheif-config.cmake
./usr/local/lib/libheif/libheif-aomdec.so
./usr/local/lib/libheif/libheif-aomenc.so
./usr/local/lib/libheif/libheif-dav1d.so
./usr/local/lib/libheif/libheif-j2kdec.so
./usr/local/lib/libheif/libheif-j2kenc.so
./usr/local/lib/libheif/libheif-jpegdec.so
./usr/local/lib/libheif/libheif-jpegenc.so
./usr/local/lib/libheif/libheif-libde265.so
./usr/local/lib/libheif/libheif-x265.so
./usr/local/lib/libheif.so.1.19.7
./usr/local/lib/pkgconfig/libheif.pc
./usr/local/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-heif.so
./usr/local/share/man/man1/heif-dec.1
./usr/local/share/man/man1/heif-enc.1
./usr/local/share/man/man1/heif-info.1
./usr/local/share/man/man1/heif-thumbnailer.1
./usr/local/share/thumbnailers/heif.thumbnailer
./gnome-platform/usr/lib/x86_64-linux-gnu/cmake/libheif/libheif-config-none.cmake
./gnome-platform/usr/lib/x86_64-linux-gnu/cmake/libheif/libheif-config-version.cmake
./gnome-platform/usr/lib/x86_64-linux-gnu/cmake/libheif/libheif-config.cmake
./gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-heif.so
./gnome-platform/usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-aomdec.so
./gnome-platform/usr/lib/x86_64-linux-gnu/libheif/plugins/libheif-libde265.so
./gnome-platform/usr/lib/x86_64-linux-gnu/libheif.so.1.17.6
./gnome-platform/usr/share/mime/image/heif.xml
```

And

```
jon@kara:/snap/gimp/current$ ldd ./usr/lib/x86_64-linux-gnu/gimp/3.0/plug-ins/file-heif/file-heif | grep heif
        libheif.so.1 => /snap/gimp/x4/usr/local/lib/libheif.so.1 (0x000072b58e581000)
```

But I still get "unsupported file type" if I try to open (any) HEIC/HEIF file·

**Comment by jnsgruk** [comment]
Aha! 

I think setting `LIBHEIF_PLUGIN_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libheif/plugins` might solve this problem, I'd missed that note in the `libheif` docs about `LIBHEIF_PLUGIN_PATH`.

Will test build now and report back!

**Comment by jnsgruk** [comment]
Success! This is GIMP opening a sample HEIF file:

![Image](https://github.com/user-attachments/assets/a7c734de-13df-40b6-ba9d-d177e44c2e57)

I'll push a new build now.

**Comment by jnsgruk** [comment]
So my previous patch *did* work, but the version of `libheif` in `core24` is too old to support some HEIC/HEIF features - specifically ones that are used by iOS 18.

I've added another commit that builds a later version of `libheif` from source, and confirmed that the resulting snap can open images taken with my iPhone: https://github.com/snapcrafters/gimp/commit/15523f5f0765a44389ea5e78da93952cd2c75138

That is [currently making its way to `latest/candidate`](https://github.com/snapcrafters/gimp/actions/runs/14386205197), but in the mean time I've uploaded a build to `latest/edge` you can test:

```
sudo snap refresh gimp --channel latest/edge
```

Let me know how it goes, and if it solves your problem, feel free to close the issue @pieroxy!

**Comment by yannos** [comment]
> Let me know how it goes,

Yes! Just tested the edge snap on Ubuntu 24.04.2 and gimp 3.0 now opens HEIC files.

Thank you @jnsgruk

**Comment by jnsgruk** [comment]
Fix now released to `latest/stable`!

**Comment by pieroxy** [comment]
Wow! That was fast. Testing right now.

**Comment by pieroxy** [comment]
I confirm I can now open HEIF files from my Phone (iPhone) and my camera (Sony Alpha 6700). 

Awesome job folks, many thanks.

**Comment by yannos** [comment]
So it seems something is still off with latest/stable... 

Using Ubuntu 24.04.2 with latest/stable snap GIMP 3.0.2 still gives the 'unknown filetype' error when opening HEIC files.

Switching to latest/edge and GIMP 3.0.2 can open HEIC files.

Switching back to latest/stable and it fails again.

Here's the output of snap info (with latest/edge installed):

> 
> name:      gimp
> summary:   GNU Image Manipulation Program
> publisher: Snapcrafters✪
> store-url: https://snapcraft.io/gimp
> contact:   https://github.com/snapcrafters/gimp/issues
> license:   MIT
> description: |
>   Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you
>   with sophisticated tools to get your job done. You can further enhance your productivity with GIMP
>   thanks to many customization options and 3rd party plugins.
>   
>   This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
>   officially maintained by the upstream developers.
>   
>   Upstream Project: https://www.gimp.org/
>   snapcraft.yaml Build Definition:
>   https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml
> commands:
>   - gimp
> snap-id:      KDHYbyuzZukmLhiogKiUksByRhXD2gYV
> tracking:     latest/edge
> refresh-date: today at 21:30 BST
> channels:
>   latest/stable:           3.0.2   2025-04-10 (515) 276MB -
>   latest/candidate:        3.0.2   2025-04-10 (515) 276MB -
>   latest/beta:             ↑                              
>   latest/edge:             3.0.2   2025-04-10 (514) 276MB -
>   preview/stable:          3.0.0   2025-03-18 (498) 323MB -
>   preview/candidate:       3.0.0   2025-03-18 (498) 323MB -
>   preview/beta:            ↑                              
>   preview/edge:            3.0.0   2025-03-18 (500) 323MB -
>   2.99-openvino/stable:    2.99.16 2025-01-21 (481) 387MB -
>   2.99-openvino/candidate: 2.99.16 2025-01-14 (481) 387MB -
>   2.99-openvino/beta:      ↑                              
>   2.99-openvino/edge:      ↑                              
> installed:                 3.0.2              (514) 276MB -

**Comment by pieroxy** [comment]
Works for me. It looks as if I have the 515 on my system while you have the 514...


```snap info gimp
name:      gimp
summary:   GNU Image Manipulation Program
publisher: Snapcrafters✪
store-url: https://snapcraft.io/gimp
contact:   https://github.com/snapcrafters/gimp/issues
license:   MIT
description: |
  Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you
  with sophisticated tools to get your job done. You can further enhance your productivity with GIMP
  thanks to many customization options and 3rd party plugins.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
  
  Upstream Project: https://www.gimp.org/
  snapcraft.yaml Build Definition:
  https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml
commands:
  - gimp
snap-id:      KDHYbyuzZukmLhiogKiUksByRhXD2gYV
tracking:     latest/stable
refresh-date: 3 days ago, at 08:44 CEST
channels:
  latest/stable:           3.0.2   2025-04-10 (515) 276MB -
  latest/candidate:        3.0.2   2025-04-10 (515) 276MB -
  latest/beta:             ↑                              
  latest/edge:             3.0.2   2025-04-10 (514) 276MB -
  preview/stable:          3.0.0   2025-03-18 (498) 323MB -
  preview/candidate:       3.0.0   2025-03-18 (498) 323MB -
  preview/beta:            ↑                              
  preview/edge:            3.0.0   2025-03-18 (500) 323MB -
  2.99-openvino/stable:    2.99.16 2025-01-21 (481) 387MB -
  2.99-openvino/candidate: 2.99.16 2025-01-14 (481) 387MB -
  2.99-openvino/beta:      ↑                              
  2.99-openvino/edge:      ↑                              
installed:                 3.0.2              (515) 276MB -
```

**Comment by yannos** [comment]
Looking at the snap info output, latest/stable is 515 (which doesn’t work on my test) and latest/edge is 514 (which does work).

**Comment by pieroxy** [comment]
You are correct, I apparently did something wrong when testing the other day... Il am constantly switching btw snap and apt version since I need HEIF support.

Version 515 doesn't work with HEIF.

**Comment by jnsgruk** [comment]
Hmm, I'll look into this. Sorry for the confusion.

**Comment by jnsgruk** [comment]
Okay, think I've got a fix. Seems I hadn't quite configured the `libheif` paths correctly - the `edge` build works out of luck due to some caching on my machine.

Will push a new build shortly.

**Comment by jnsgruk** [comment]
https://github.com/snapcrafters/gimp/actions/runs/14444127777 -- on it's way!

**Comment by jnsgruk** [comment]
See #412
